### PR TITLE
Fix #23

### LINKED ISSUE #23: Update Shenzhen line 14,16,20
> Official Website: htps://www.szmc.net/map/
> Line color of Shenzhen metro Line 20 was changed. The color code of line 20 should be 9CD0CB.
> For line 14 and line 16. The line color codes should be F2C75C and 1E22AA (data from Wikipedia)

_Originally posted by @linchen1965 in https://github.com/wongchito/RailMapGenerator/issues/250_

### PR DESCRIPTION
**Pull request by XHG78999**
#23 Update palettes for Shenzhen

Co-Authored-By: linchen1965 <92020676+linchen1965@users.noreply.github.com>

### CODE REVIEW

**Review by wongchito — CHANGES_REQUESTED** [review]
Could your revert the path of this file (from 公共 to public)

**Comment by XHG78999** [comment]
Looks like its break from the github add him translations. I will try to fix it.

**Comment by wongchito** [comment]
> Looks like its break from the github add him translations. I will try to fix it.

Oh I see. If it's too hard maybe you can resubmit a PR by editing online and copying the entire commit message. 

Btw, may I ask what's the source of the colours?

**Comment by XHG78999** [comment]
> > Looks like its break from the github add him translations. I will try to fix it.
> 
> Oh I see. If it's too hard maybe you can resubmit a PR by editing online and copying the entire commit message. 
> 
> Btw, may I ask what's the source of the colours?

linchen1965 said, he search these colors from Wikipedia and SZMetro official website.

**Comment by wongchito** [comment]
Covered in 273320bb

**Pull request closed without merging**
